insert into category(id, name) values (1, 'Adventure stories');
insert into category(id, name) values (2, 'Classics');
insert into category(id, name) values (3, 'Crime');
insert into category(id, name) values (4, 'Fairy tales, fables, and folk tales');
insert into category(id, name) values (5, 'Fantasy');
insert into category(id, name) values (6, 'Historical fiction');
insert into category(id, name) values (7, 'Horror');
insert into category(id, name) values (8, 'Humour and satire');
insert into category(id, name) values (9, 'Literary fiction');
insert into category(id, name) values (10, 'Mystery');
insert into category(id, name) values (11, 'Poetry');
insert into category(id, name) values (12, 'Plays');
insert into category(id, name) values (13, 'Romance');
insert into category(id, name) values (14, 'Science fiction');
insert into category(id, name) values (15, 'Short stories');
insert into category(id, name) values (16, 'Thrillers');
insert into category(id, name) values (17, 'War');
insert into category(id, name) values (18, 'Women’s fiction');
insert into category(id, name) values (19, 'Young adult');
insert into category(id, name) values (20, 'Autobiography and memoir');
insert into category(id, name) values (21, 'Biography');
insert into category(id, name) values (22, 'Essays');
insert into category(id, name) values (23, 'Non-fiction novel');
insert into category(id, name) values (24, 'Self-help');